# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: maserrie <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/14 17:56:37 by maserrie          #+#    #+#              #
#    Updated: 2022/11/15 02:37:25 by maserrie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = main.c
SRCS += ft_print.c
SRCS += ft_atoi.c
SRCS += ft_putnbr.c
SRCS += ft_operation.c

HEADERS = ft.h

CFLAGS = -Wall -Werror -Wextra -g

OBJS = ${SRCS:.c=.o}

CC = gcc

RM = rm -f

NAME = do-op

${NAME}: ${OBJS}
	${CC} -o ${NAME} -I ${HEADERS} ${CFLAGS} ${OBJS}

all: NAME

clean:
	${RM} ${OBJS}

fclean: clean
	${RM} ${NAME}
